name: EAC CI Pipeline

on:
  push:
    branches: [ develop, master ]

jobs:
  validate-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install tfsec checkov pytest boto3

    - name: Terraform Init & Validate
      run: |
        terraform init
        terraform validate

    - name: Run PyTest
      run: pytest tests/

    - name: Run Security Scan
      run: tfsec generated || true

    - name: Trigger Spinnaker
      run: |
        curl -X POST http://spinnaker:8084/webhooks/trigger/pipeline \
          -H "Content-Type: application/json" \
          -d '{"trigger": "GitHubAction", "status": "passed"}'
