name: Terraform Plan (PR Review)

on:
  pull_request:
    paths:
      - 'infra/**'

env:
  TF_WORKSPACE: automated-testing
  TF_ORGANIZATION: smriti-aws
  AWS_REGION: us-east-1
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
  TF_VERSION: 1.6.6
  PYTHON_VERSION: 3.11

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init \
            -backend-config="organization=${TF_ORGANIZATION}" \
            -backend-config="workspaces.name=${TF_WORKSPACE}"

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Upload Plan as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: infra/tfplan

   