name: Terraform ECS Pipeline with TFC Backend

on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]
  delete:

env:
  # Environment variables for Terraform Cloud
  AWS_REGION: us-east-1
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }} # Ensure this secret exists in your repository settings, or update to the correct secret name.
  TF_VERSION: 1.6.6
  PYTHON_VERSION: 3.11
  MODULES_DIR: infra

jobs:

  validate-plan:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: infra
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init (TFC Backend)
        run: |
          terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: plan.out

  apply-on-main:
    name: Terraform Apply
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: validate-plan
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init (TFC)
        run: |
          terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve

  # destroy-on-delete:
  #   name: Terraform Destroy
  #   runs-on: ubuntu-latest
  #   # if: github.event_name == 'delete' && github.event.ref_type == 'branch' && github.event.ref == 'main'
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: ${{ env.TF_VERSION }}

  #     - name: Terraform Init (TFC)
  #       run: |
  #         terraform init

  #     - name: Terraform Destroy
  #       run: terraform destroy -auto-approve
